### ISSUE TITLE
Remove Python references from compiler

### ISSUE THREAD

**Issue by haskellcamargo** [quack/quack#12]
Currently, the Quack compiler is generating some sort of Python right from the AST. This is definitely not the best approach. After, we'll implement the typechecker and the code generation will only happen after this. Thinking in this way, we need to remove all the Python references (methods and usages) from the compiler. If you want to locate more references, you can `grep -r -i python` the project. Most of the usages are under `src/ast/expr` and `src/ast/stmt`.
### TODO list
- [x] Remove the reference from [Makefile](https://github.com/quack/quack/blob/master/Makefile#L10)
- [x] Remove methods from [`src/ast/expr`](https://github.com/quack/quack/tree/master/src/ast/expr)
- [x] Remove methods from [`src/ast/stmt`](https://github.com/quack/quack/tree/master/src/ast/stmt)
- [x] Remove reference from [Quack REPL](https://github.com/quack/quack/blob/master/src/repl/QuackRepl.php#L83)
- [x] Remove method from [TokenReader](https://github.com/quack/quack/blob/master/src/parser/TokenReader.php#L83-88)
